# Generated by Django 4.1.3 on 2022-12-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo_del_Proyecto', models.CharField(max_length=200)),
                ('Descripcion_del_Proyecto', models.CharField(max_length=200)),
                ('Tags', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
